### ISSUE TITLE
How to use the MIS?

### ISSUE THREAD

**Issue by GongSiqiu** [jakeffbulmer/gbs#2]
Hello!
I tried to use the code to generate samples. However, it is strange that all the samples have same photon number.
```
N = int(np.round(mean_clicks(cov)))
mis = ClickMIS(cov, N)
mis.run_chain(3000)

burn_in = 500 
thinning_rate = 3

MISsample=np.array(mis.chain_patterns[burn_in::thinning_rate])
```
![图片](https://user-images.githubusercontent.com/40697840/164509705-2d7844a5-5d99-4d52-bacd-9aea77c92e0b.png)
![图片](https://user-images.githubusercontent.com/40697840/164509770-8f8a4e2f-9ad2-4182-b577-695449fca145.png)

**Comment by jakeffbulmer** [comment]
Our MIS algorithm is designed to sample from the fixed photon number / fixed click number subspace of the distribution. This is what the variable N is defining when you initialise the clickMIS class in your code snippet.

We did this partly because it made it slightly more straightforward to derive the algorithm, but we thought this is one reason to choose MIS over the chain rule. If you want to sample within a fixed click number subspace, you can run MIS and then you do not have to post select the samples.

Otherwise, I would normally advise using the chain rule as there is no inherent autocorrelation between samples, whereas in MIS there can be autocorrelation when the thinning rate is not sufficiently high.

**Comment by GongSiqiu** [comment]
Thanks a lot!
